name: Generate CV PDF

on:
  push:
    paths:
      - docs/cv.md
      - .github/workflows/export-cv.yml
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Publish Markdown As PDF
        uses: shrink/actions-document-publish@v1
        id: publish-doc
        with:
          sources: "docs/cv.md"

      - name: Upload generated PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: ${{ steps.publish-doc.outputs.pdf }}
