name: Export CV

on:
  push:
    paths:
      - "docs/cv.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pandoc + wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Generate PDF
        shell: bash
        run: |
          # 1) Crear los fragmentos HTML/CSS
          cat > header.html <<'EOF'
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown.min.css">
          <style>
            @page { size: A4; margin: 10mm; }
            html, body { margin: 0; padding: 0; }
            .markdown-body { box-sizing: border-box; max-width: none; margin: 0; padding: 0; }
              body, .markdown-body { 
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
              font-size: 12px; line-height: 1.5;
              -webkit-print-color-adjust: exact; print-color-adjust: exact;
            }
            .markdown-body h1 { font-size: 22px; margin: 0 0 10px; }
            .markdown-body h2 { font-size: 18px; margin: 18px 0 8px; }
            .markdown-body h3 { font-size: 15px; margin: 14px 0 6px; }
            .markdown-body p, .markdown-body li { font-size: 12px; }
            .markdown-body ul, .markdown-body ol { margin: 0 0 8px 18px; }
            .markdown-body table { width: 100%; font-size: 11px; }
            .markdown-body pre, .markdown-body code { font-size: 11px; }
            .markdown-body img { max-width: 100%; }
            .markdown-body a { color: inherit; text-decoration: none; }
            h1, h2, h3 { page-break-after: avoid; }
            pre, blockquote, table, ul, ol { page-break-inside: avoid; }
          </style>
          EOF

              echo '<article class="markdown-body">' > before.html
              echo '</article>' > after.html

              pandoc docs/cv.md -o docs/cv.pdf \
                --from gfm \
                --standalone \
                --metadata title="CV César Nóvoa" \
                --include-in-header=header.html \
                --include-before-body=before.html \
                --include-after-body=after.html \
                --pdf-engine=wkhtmltopdf \
                --pdf-engine-opt=--page-size --pdf-engine-opt=A4 \
                --pdf-engine-opt=--margin-top --pdf-engine-opt=10mm \
                --pdf-engine-opt=--margin-right --pdf-engine-opt=10mm \
                --pdf-engine-opt=--margin-bottom --pdf-engine-opt=10mm \
                --pdf-engine-opt=--margin-left --pdf-engine-opt=10mm \
                --pdf-engine-opt=--header-spacing --pdf-engine-opt=0 \
                --pdf-engine-opt=--footer-spacing --pdf-engine-opt=0

      - name: Commit PDF back
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/cv.pdf
          git commit -m "chore: update CV.pdf [skip ci]" || echo "No changes to commit"
          git push
