name: Export CV

on:
  push:
    paths:
      - "docs/cv.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pandoc + wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Generate PDF
        run: |
          pandoc docs/cv.md -o docs/cv.pdf \
            --from markdown \
            --standalone \
            --metadata title="CV César Nóvoa" \
            --include-in-header=<(echo '<style>
              body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji","Segoe UI Emoji"; }
              .markdown-body { box-sizing: border-box; min-width: 200px; max-width: 980px; margin: 0 auto; padding: 45px; }
              @media (max-width: 767px) { .markdown-body { padding: 15px; } }
            </style>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown.min.css">') \
            --pdf-engine=wkhtmltopdf \
            -V geometry:margin=2cm

      - name: Commit PDF back
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/cv.pdf
          git commit -m "chore: update CV.pdf [skip ci]" || echo "No changes to commit"
          git push
