name: Export CV

on:
  push:
    paths:
      - "docs/cv.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pandoc + wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Generate PDF
        run: |
          pandoc docs/cv.md -o docs/cv.pdf \
            --from markdown \
            --css https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown.min.css \
            --pdf-engine=wkhtmltopdf -V geometry:margin=2cm

      - name: Commit PDF back
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/cv.pdf
          git commit -m "chore: update CV.pdf [skip ci]" || echo "No changes to commit"
          git push
